<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title><?php echo $title; ?></title>
		<meta name="viewport" content="width=device-width">

		<link rel="stylesheet" type="text/css" href="/vendor/anchorcms/anchor-core/assets/css/styles.css">
		<link rel="stylesheet" type="text/css" href="/vendor/anchorcms/anchor-core/assets/icons/stroke.css">
		<link href="//fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">
	</head>
	<body>
		<?php echo $body; ?>
	</body>
</html>