<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title><?php echo $title; ?></title>
		<meta name="viewport" content="width=device-width">

		<link rel="stylesheet" type="text/css" href="/vendor/anchorcms/anchor-core/assets/css/styles.css">

	</head>
	<?php printf('<body class="%s">', $class); ?>
		<?php echo $body; ?>

		<script src="/vendor/anchorcms/anchor-core/assets/js/jquery.js"></script>
		<script src="/vendor/anchorcms/anchor-core/assets/js/retina.js"></script>
	</body>
</html>