<form method="post" action="<?php echo $action; ?>" accept-charset="utf-8">
	<input name="token" type="hidden" value="<?php echo $token; ?>">

	<?php echo $messages; ?>

	<p><label>Username
	<input name="user" value="<?php echo $user; ?>" placeholder="Username"></label></p>

	<p><label>Password
	<input name="pass" type="password" placeholder="Password"></label></p>

	<p><button class="btn" type="submit">Log In</button></p>
</form>