<?php echo $form->open(); ?>
	<?php echo $form->getElement('token')->getHtml(); ?>

	<?php echo $messages; ?>

	<img class="logo" alt="Anchor logo" src="/vendor/anchorcms/anchor-core/assets/img/logo-login.png">

	<p>
		<?php echo $form->getElement('user')->getHtml(); ?>
		<label for="<?php echo $form->getElement('user')->getName(); ?>" class="flaticon user-1"><?php echo $form->getElement('user')->getLabel(); ?>:</label>
	</p>

	<p>
		<?php echo $form->getElement('pass')->getHtml(); ?>
		<label for="<?php echo $form->getElement('pass')->getName(); ?>" class="flaticon password"><?php echo $form->getElement('pass')->getLabel(); ?>:</label>
	</p>

	<p><?php echo $form->getElement('login')->getHtml(); ?></p>
<?php echo $form->close(); ?>