<?php echo $menu; ?>

<section class="list">
	<h4 class="intro">Categories</h4>
	<ul>
		<?php foreach($categories as $category): ?>
		<li>
			<a href="<?php echo $this->getHelper('uri')->to('admin/categories/'.$category->id.'/edit'); ?>">
				<?php echo $category->title; ?>
				<span><?php echo $category->description; ?></span>
			</a>
		</li>
		<?php endforeach; ?>
	</ul>
</section>

<main class="content">
	<hgroup>
		<h1><?php echo $title; ?></h1>
	</hgroup>
</main>
