<?php echo $menu; ?>

<section class="list">
	<h4 class="intro">Categories</h4>
	<ul>
		<?php foreach($categories as $category): ?>
		<li>
			<a href="<?php echo $this->getHelper('uri')->to('admin/categories/'.$category->id.'/edit'); ?>">
				<?php echo $category->title; ?>
				<span><?php echo $category->description; ?></span>
			</a>
		</li>
		<?php endforeach; ?>
	</ul>
</section>

<main class="content">
	<a class="btn top-right" href="<?php echo $this->getHelper('uri')->to('admin/categories/create'); ?>">New category</a>
	<span class="empty-state flaticon feather-1">Click a category on the left to edit, or add a category at the top-right.</span>
</main>
