<?php echo $menu; ?>

<section class="list">
	<h4 class="intro">Pages</h4>
	<ul>
		<?php foreach($pages as $page): ?>
		<li>
			<a href="<?php echo $this->getHelper('uri')->to('admin/pages/'.$page->id.'/edit'); ?>">
				<?php echo $page->title; ?>
				<span><?php echo $page->slug; ?></span>
			</a>
		</li>
		<?php endforeach; ?>
	</ul>
</section>

<main class="content">
	<a class="btn top-right" href="<?php echo $this->getHelper('uri')->to('admin/pages/create'); ?>">New page</a>
	<span class="empty-state flaticon feather-1">Click a page on the left to edit, or add a page at the top-right.</span>
</main>
