<?php echo $menu; ?>

<section class="list">
	<h4 class="intro">Users</h4>
	<ul>
		<?php foreach($users as $user): ?>
		<li>
			<a href="<?php echo $this->getHelper('uri')->to('admin/users/'.$user->id.'/edit'); ?>">
				<?php echo $user->real_name; ?>
				<span><?php echo $user->role; ?></span>
			</a>
		</li>
		<?php endforeach; ?>
	</ul>
</section>

<main class="content">
	<a class="btn top-right" href="<?php echo $this->getHelper('uri')->to('admin/user/create'); ?>">New user</a>
	<span class="empty-state flaticon feather-1">Click a user on the left to edit, or add a user at the top-right.</span>
</main>
