<?php echo $menu; ?>

<section class="list">
	<ul>
		<?php foreach($posts as $post): ?>
		<li>
			<a href="<?php echo $this->getHelper('uri')->to('admin/posts/'.$post->id.'/edit'); ?>">
				<?php echo $post->title; ?>
				<time><?php echo date('jS M Y', strtotime($post->created)); ?></time>
			</a>
		</li>
		<?php endforeach; ?>
	</ul>
</section>

<main class="content">
	<hgroup>
		<h1><?php echo $title; ?></h1>
	</hgroup>
</main>
