<?php echo $menu; ?>

<section class="list">
	<h4 class="intro">Posts</h4>
	<ul>
		<?php foreach($posts as $post): ?>
		<li>
			<a href="<?php echo $this->getHelper('uri')->to('admin/posts/'.$post->id.'/edit'); ?>">
				<?php echo $post->title; ?>
				<time><?php echo date('jS M Y', strtotime($post->created)); ?></time>
			</a>
		</li>
		<?php endforeach; ?>
	</ul>
</section>

<main class="content">
	<a class="btn top-right" href="<?php echo $this->getHelper('uri')->to('admin/posts/create'); ?>">New post</a>
	<span class="empty-state flaticon feather-1">Click a post on the left to edit, or add a post at the top-right.</span>
</main>